spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowed-headers: "*"
      routes:
        - id: authentication-service-register
          uri: lb://authentication-service
          predicates:
            - Path=/register
        - id: authentication-service-authenticate
          uri: lb://authentication-service
          predicates:
            - Path=/authenticate
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**
          filters:
            - JwtFilterFactory
