spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service-register
          uri: lb://authentication-service
          predicates:
            - Path=/register
        - id: authentication-service-authenticate
          uri: lb://authentication-service
          predicates:
            - Path=/authenticate
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**
          filters:
            - JwtFilterFactory
